on:
  workflow_call:
    secrets:
      NUGET_GITHUB_USERNAME:
        required: true
      GITHUB_TOKEN:
        required: true

    inputs:
      ref:
        type: string
        required: true
      dotnet_version:
        type: string
        default: 8.x
      version:
        type: string
        required: true
      configuration:
        type: string
        default: Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ inputs.ref }}
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
    
      - name: Add Github nuget repo
        run: dotnet nuget add source --username ${{ secrets.NUGET_GITHUB_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/TostOrg/index.json"
    
      - name: Restore dependencies
        run: dotnet restore "**/*.sln" --no-cache
    
      - name: Build
        run: dotnet build "**/*.sln" --no-restore --configuration ${{ inputs.configuration }} -p:Version=${{ inputs.version }}
    
      - name: Test
        run: dotnet test "**/*.sln" --no-build --configuration ${{ inputs.configuration }} --verbosity normal -p:Version=${{ inputs.version }}
